# Generated by Django 6.0.7 on 2026-07-27 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_title', models.CharField(default="Welcome to St. Mary's LP School", max_length=200)),
                ('intro_content', models.TextField(default="For over five decades, St. Mary's LP School has been a guiding light in early childhood education. We believe that every child is unique and full of potential. Our warm, nurturing environment is designed to stimulate curiosity, foster creativity, and build a strong foundation of values that lasts a lifetime.")),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('principal_title', models.CharField(default="Principal's Message", max_length=200)),
                ('principal_name', models.CharField(default='Sr. Mary Teresa, Headmistress', max_length=150)),
                ('principal_message', models.TextField(default="Dear Parents and Well-wishers, Welcome to our joyful family! At St. Mary's, education is not just about textbooks; it is about laughter, discovery, and learning to care for one another. We strive to create a second home where your little ones feel safe, loved, and inspired. Together, let us guide them as they take their first steps towards a bright future.")),
                ('principal_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('principal_signature', models.CharField(default='Sr. Mary Teresa', max_length=150)),
                ('parallax_bg', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('parallax_text', models.TextField(default='Educating the mind without educating the heart is no education at all.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='book', help_text='Common names like: book, palette, heart, sports, globe, star, music', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('value', models.CharField(help_text='e.g. 100%, 25+, 1st Place', max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('news', 'News & Updates'), ('circular', 'Circulars'), ('notice', 'School Notices')], default='notice', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='events/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='facilities/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='gallery/')),
                ('date', models.DateField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default="St. Mary's Lower Primary School", max_length=200)),
                ('school_motto', models.CharField(default='Nurturing Hearts, Inspiring Minds', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_bg', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_heading', models.CharField(default='Where Learning is a Joyful Adventure', max_length=300)),
                ('hero_cta_text', models.CharField(default='Explore Our World', max_length=100)),
                ('hero_cta_link', models.CharField(default='#about', max_length=100)),
                ('phone', models.CharField(default='+91 484 2345678', max_length=100)),
                ('email', models.EmailField(default='info@stmaryslpschool.edu.in', max_length=254)),
                ('address', models.TextField(default="St. Mary's LP School, Church Road, Ernakulam, Kerala, PIN - 682011")),
                ('map_iframe', models.TextField(blank=True, default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3929.5678910111!2d76.2811!3d9.9723" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>', null=True)),
                ('social_facebook', models.URLField(blank=True, default='https://facebook.com', null=True)),
                ('social_instagram', models.URLField(blank=True, default='https://instagram.com', null=True)),
                ('social_youtube', models.URLField(blank=True, default='https://youtube.com', null=True)),
                ('social_twitter', models.URLField(blank=True, default='https://twitter.com', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/additional/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='school.event')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='school.galleryalbum')),
            ],
        ),
    ]
