# Generated by Django 6.0.7 on 2026-07-28 09:08

import school.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', validators=[school.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='parallax_bg',
            field=models.ImageField(blank=True, null=True, upload_to='about/', validators=[school.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', validators=[school.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('news', 'News & Updates'), ('circular', 'Circulars'), ('notice', 'School Notices')], db_index=True, default='notice', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='announcements/', validators=[school.validators.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(upload_to='events/', validators=[school.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='events/additional/', validators=[school.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(upload_to='facilities/', validators=[school.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='cover_image',
            field=models.ImageField(upload_to='gallery/', validators=[school.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(upload_to='gallery/photos/', validators=[school.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='hero_bg',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[school.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='hero_heading',
            field=models.CharField(default='Learning is a Joyful Adventure', max_length=300),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[school.validators.validate_image_file]),
        ),
    ]
