# Generated by Django 6.0.7 on 2026-07-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_aboutsection_intro_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesetting',
            name='map_iframe',
        ),
    ]
